package com.lemuel.ganamrs.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lemuel.ganamrs.entity.GankGril;

import com.lemuel.ganamrs.greendao.GankGrilDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gankGrilDaoConfig;

    private final GankGrilDao gankGrilDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gankGrilDaoConfig = daoConfigMap.get(GankGrilDao.class).clone();
        gankGrilDaoConfig.initIdentityScope(type);

        gankGrilDao = new GankGrilDao(gankGrilDaoConfig, this);

        registerDao(GankGril.class, gankGrilDao);
    }
    
    public void clear() {
        gankGrilDaoConfig.clearIdentityScope();
    }

    public GankGrilDao getGankGrilDao() {
        return gankGrilDao;
    }

}
